#!/usr/bin/env python3
"""Streamlit web demo for AI-human text detection."""

import sys
from pathlib import Path

import streamlit as st

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from multilingual_ai_detection.models import load_model

# Page config
st.set_page_config(
    page_title="AI-Human Text Detection",
    page_icon="🤖",
    layout="wide"
)

# Load model (cache it)
@st.cache_resource
def load_trained_model():
    """Load the trained model."""
    model_path = "models/statistical"
    model_type = "statistical"

    try:
        model = load_model(model_path, model_type)
        return model
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

def main():
    st.title("🤖 Multilingual AI-Human Text Detection")
    st.markdown("""
    This demo uses a machine learning model to detect whether text was written by a human or generated by AI.
    The model supports multiple languages including English, Chinese, and Vietnamese.
    """)

    # Load model
    model = load_trained_model()

    if model is None:
        st.error("Model could not be loaded. Please check that the model files exist.")
        return

    # Input section
    st.header("📝 Text Input")

    col1, col2 = st.columns([2, 1])

    with col1:
        text_input = st.text_area(
            "Enter text to analyze:",
            height=200,
            placeholder="Paste your text here...",
            help="Enter any text in English, Chinese, or Vietnamese"
        )

    with col2:
        return_probabilities = st.checkbox(
            "Show detailed probabilities",
            help="Display confidence scores for both classes"
        )

        analyze_button = st.button(
            "🔍 Analyze Text",
            type="primary",
            use_container_width=True
        )

    # Analysis section
    if analyze_button and text_input.strip():
        with st.spinner("Analyzing text..."):
            try:
                # Make prediction
                predictions = model.predict([text_input])
                probabilities = model.predict_proba([text_input])

                prediction = predictions[0]
                prob = probabilities[0]

                class_names = ["Human", "AI"]
                predicted_class = class_names[prediction]

                # Display results
                st.header("📊 Analysis Results")

                # Main result
                if prediction == 0:  # Human
                    st.success(f"**Prediction: {predicted_class}** 🎉")
                    st.markdown("This text appears to be written by a human.")
                else:  # AI
                    st.warning(f"**Prediction: {predicted_class}** 🤖")
                    st.markdown("This text appears to be generated by AI.")

                # Confidence
                confidence = max(prob) if isinstance(prob, list) else prob
                st.metric("Confidence", f"{confidence:.1%}")

                # Detailed probabilities
                if return_probabilities:
                    st.subheader("Detailed Probabilities")

                    if isinstance(prob, list):
                        prob_df = {
                            "Class": class_names,
                            "Probability": [f"{p:.1%}" for p in prob]
                        }

                        # Highlight predicted class
                        colors = ["🟢" if i == prediction else "⚪" for i in range(len(class_names))]
                        prob_df[" "] = colors

                        st.table(prob_df)
                    else:
                        st.info(f"Score: {prob:.4f}")

            except Exception as e:
                st.error(f"Error during analysis: {e}")

    elif analyze_button and not text_input.strip():
        st.warning("Please enter some text to analyze.")

    # Information section
    st.header("ℹ️ About")

    with st.expander("How it works"):
        st.markdown("""
        This model uses transformer-based neural networks trained on a multilingual dataset
        containing both human-written and AI-generated text. The model analyzes linguistic
        patterns, writing style, and other features to make its classification.

        **Supported Languages:**
        - English
        - Chinese
        - Vietnamese

        **Model Architecture:**
        - XLM-RoBERTa for multilingual understanding
        - Fine-tuned for binary classification
        """)

    with st.expander("Dataset Information"):
        st.markdown("""
        The model was trained on a balanced dataset including:
        - **English**: HC3 dataset (reddit_eli5 subset)
        - **Chinese**: HC3-Chinese dataset (open_qa subset)
        - **Vietnamese**: Custom crawled data from Vietnamese Reddit communities

        Each language contains 300 question-answer pairs with both human and AI responses.
        """)

    with st.expander("Limitations"):
        st.markdown("""
        - The model's accuracy may vary depending on text length and language
        - Very short texts may be harder to classify accurately
        - The model may not perform well on highly specialized or technical content
        - AI models are constantly improving, so detection accuracy may change over time
        """)

if __name__ == "__main__":
    main()